version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-video-editor
    ports:
      - "9017:9017"
    env_file: .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 9017 --reload
